### PR TITLE
Remove package-lock

### PR DESCRIPTION
**Pull request by stvstnfrd**
I don't think we need this any more,
since we aren't using `grunt` or any other NPM packages.

### CODE REVIEW

**Comment by stvstnfrd** [comment]
I updated the tests, as  they caused the build to fail.

**Review by caesar2164 — COMMENTED** [review]
@stvstnfrd could you add a comment saying that the plurals were changed to `AssertEqual` for python 3 compatibility?

**Comment by stvstnfrd** [comment]
@caesar2164 I added a comment and link to documentation in the commit message about the py3 deprecation.

**Review by caesar2164 — APPROVED** [review]
doh!

**Pull request merged**
